###

CapsLock.js

An object allowing the status of the caps lock key to be determined

Created by Stephen Morley - http://code.stephenmorley.org/ - and released under
the terms of the CC0 1.0 Universal legal code:

http://creativecommons.org/publicdomain/zero/1.0/legalcode

###
define [""], () ->
  do ->
    _1 = false
    _2 = []
    _3 = /Mac/.test(navigator.platform)

    _4 = ->
      _1

    _5 = (_6) ->
      _2.push _6
      return

    _7 = (e) ->
      if !e
        e = window.event
      _8 = _1
      _9 = if e.charCode then e.charCode else e.keyCode
      if _9 >= 97 and _9 <= 122
        _1 = e.shiftKey
      else
        if _9 >= 65 and _9 <= 90 and !(e.shiftKey and _3)
          _1 = !e.shiftKey
      if _1 != _8
        _a = 0
        while _a < _2.length
          _2[_a] _1
          _a++
      return

    if window.addEventListener
      window.addEventListener 'keypress', _7, false
    else
      document.documentElement.attachEvent 'onkeypress', _7
    {
      isOn: _4
      addListener: _5
    }

  # ---
  # generated by js2coffee 2.1.0